package com.flashsale.coupon;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.util.*;
@Repository class CouponTemplateRepository {private final JdbcTemplate jdbc;CouponTemplateRepository(JdbcTemplate j){jdbc=j;}
 CouponTemplate create(CouponTemplate x){return jdbc.queryForObject("insert into coupon_template(name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,created_by,updated_by) values(?,?,?,?,?,?,?,?,?,?,?) returning id,name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,status,updated_by",(r,n)->map(r),x.name(),x.thresholdMinor(),x.discountMinor(),x.issueLimit(),x.claimLimitPerUser(),x.claimStartsAt(),x.claimEndsAt(),x.useStartsAt(),x.useEndsAt(),x.updatedBy(),x.updatedBy());}
 CouponTemplate update(long id,CouponTemplate x){try{return jdbc.queryForObject("update coupon_template set name=?,threshold_minor=?,discount_minor=?,issue_limit=?,claim_limit_per_user=?,claim_starts_at=?,claim_ends_at=?,use_starts_at=?,use_ends_at=?,updated_by=?,version=version+1 where id=? and issued_count=0 returning id,name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,status,updated_by",(r,n)->map(r),x.name(),x.thresholdMinor(),x.discountMinor(),x.issueLimit(),x.claimLimitPerUser(),x.claimStartsAt(),x.claimEndsAt(),x.useStartsAt(),x.useEndsAt(),x.updatedBy(),id);}catch(org.springframework.dao.EmptyResultDataAccessException e){return null;}}
 CouponTemplate status(long id,String s,long a){try{return jdbc.queryForObject("update coupon_template set status=?,updated_by=?,version=version+1 where id=? returning id,name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,status,updated_by",(r,n)->map(r),s,a,id);}catch(org.springframework.dao.EmptyResultDataAccessException e){return null;}}
 CouponTemplate get(long id){return jdbc.query("select id,name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,status,updated_by from coupon_template where id=?",r->r.next()?map(r):null,id);}
 List<CouponTemplate> list(boolean active){return jdbc.query("select id,name,threshold_minor,discount_minor,issue_limit,claim_limit_per_user,claim_starts_at,claim_ends_at,use_starts_at,use_ends_at,status,updated_by from coupon_template "+(active?"where status='ACTIVE' and now() between claim_starts_at and claim_ends_at ":"")+"order by id",(r,n)->map(r));}
 private CouponTemplate map(java.sql.ResultSet r)throws java.sql.SQLException{return new CouponTemplate(r.getLong(1),r.getString(2),r.getLong(3),r.getLong(4),r.getInt(5),r.getInt(6),r.getObject(7,java.time.OffsetDateTime.class),r.getObject(8,java.time.OffsetDateTime.class),r.getObject(9,java.time.OffsetDateTime.class),r.getObject(10,java.time.OffsetDateTime.class),r.getString(11),r.getLong(12));}
}
