package com.flashsale.coupon;
import com.flashsale.common.security.Principal;import com.flashsale.common.trace.TraceContext;import org.springframework.dao.EmptyResultDataAccessException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.UUID;
@Service class CouponClaimService {private final JdbcTemplate jdbc;CouponClaimService(JdbcTemplate j){jdbc=j;}
 @Transactional long claim(Principal p,long templateId,String key){if(p==null||p.role()!=com.flashsale.common.security.Role.CUSTOMER)throw new IllegalArgumentException("FORBIDDEN");if(key==null||key.isBlank())throw new IllegalArgumentException("VALIDATION_ERROR");try{jdbc.update("insert into coupon_claim_idempotency(user_id,coupon_template_id,idempotency_key,request_fingerprint) values(?,?,?,?)",p.userId(),templateId,key,Integer.toHexString(key.hashCode()));}catch(Exception e){Long prior=jdbc.query("select user_coupon_id from coupon_claim_idempotency where user_id=? and coupon_template_id=? and idempotency_key=?",r->r.next()?r.getObject(1,Long.class):null,p.userId(),templateId,key);if(prior!=null)return prior;throw new IllegalArgumentException("REQUEST_IN_PROGRESS");}
  try {jdbc.queryForObject("update coupon_template set issued_count=issued_count+1,version=version+1 where id=? and status='ACTIVE' and now() between claim_starts_at and claim_ends_at and issued_count<issue_limit returning id",Long.class,templateId);}catch(EmptyResultDataAccessException e){throw new IllegalArgumentException("COUPON_NOT_AVAILABLE");}
  jdbc.update("insert into coupon_user_claim_counter(coupon_template_id,user_id,claimed_count) values(?,?,1) on conflict(coupon_template_id,user_id) do update set claimed_count=coupon_user_claim_counter.claimed_count+1",templateId,p.userId());Integer count=jdbc.queryForObject("select claimed_count from coupon_user_claim_counter where coupon_template_id=? and user_id=?",Integer.class,templateId,p.userId());Integer limit=jdbc.queryForObject("select claim_limit_per_user from coupon_template where id=?",Integer.class,templateId);if(count==null||limit==null||count>limit)throw new IllegalArgumentException("COUPON_CLAIM_LIMIT_EXCEEDED");
  Long coupon=jdbc.queryForObject("insert into user_coupon(coupon_template_id,user_id) values(?,?) returning id",Long.class,templateId,p.userId());jdbc.update("update coupon_claim_idempotency set status='SUCCEEDED',user_coupon_id=?,response_code='SUCCESS',completed_at=now() where user_id=? and coupon_template_id=? and idempotency_key=?",coupon,p.userId(),templateId,key);jdbc.update("insert into coupon_outbox(event_id,event_type,idempotency_key,aggregate_type,aggregate_id,payload,trace_id) values(?,?,?,?,?,?,?)",UUID.randomUUID(),"COUPON_CLAIMED","COUPON_CLAIM_"+key,"USER_COUPON",coupon,"{\"template_id\":"+templateId+",\"user_id\":"+p.userId()+"}",TraceContext.getOrCreate());return coupon;
 }
}
