package com.flashsale.payment;
import com.flashsale.order.*; import java.time.*; import java.util.*; import java.util.concurrent.ConcurrentHashMap;
public final class PaymentService {
 private final OrderRepository orders; private final PaymentGateway gateway; private final Clock clock; private final Map<String,Result> idempotency=new ConcurrentHashMap<>(); private final Set<String> events=ConcurrentHashMap.newKeySet();
 public PaymentService(OrderRepository orders,PaymentGateway gateway,Clock clock){this.orders=orders;this.gateway=gateway;this.clock=clock;}
 public synchronized Result pay(long userId,String orderNumber,String key,long amount,String currency,String status){String ik=userId+":"+orderNumber+":"+key; if(idempotency.containsKey(ik))return idempotency.get(ik); Order o=orders.findByNumber(orderNumber).orElseThrow(); if(o.userId()!=userId)throw new IllegalArgumentException("FORBIDDEN"); if(o.status()!=Order.Status.PENDING_PAYMENT)throw new IllegalArgumentException("ORDER_NOT_PAYABLE"); if(o.payableAmountMinor()!=amount||!o.currency().equals(currency))throw new IllegalArgumentException("PAYMENT_AMOUNT_MISMATCH"); if(!o.expiresAt().isAfter(OffsetDateTime.now(clock)))throw new IllegalArgumentException("ORDER_EXPIRED"); var r=gateway.initiate(new PaymentGateway.PaymentRequest(orderNumber,amount,currency,status)); var result=new Result(r.success(),r.transactionId(),r.failureCode()); idempotency.put(ik,result); if(r.success()){var paid=new Order(o.orderNumber(),o.userId(),o.kind(),o.activityId(),o.itemSubtotalMinor(),o.activityDiscountMinor(),o.couponDiscountMinor(),o.payableAmountMinor(),o.currency(),Order.Status.COMPLETED,o.expiresAt(),o.items());orders.save(paid);} return result; }
 public synchronized Result callback(PaymentGateway.CallbackRequest request){var c=gateway.verifyAndParse(request);if(!events.add(c.eventId()))return new Result(true,c.transactionId(),null);return new Result(c.success(),c.transactionId(),c.success()?null:"PAYMENT_FAILED");}
 public record Result(boolean success,String transactionId,String failureCode){}
}
